language: c
sudo: false

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install md5sha1sum; fi
  - source devtools/travis-ci/install_miniconda.sh
  # Sets up a MINIConda enviroment in the name of the selected python version
  - source devtools/ci/install.sh
  # Do not buffer output of python outputs but flush them directly to the terminal
  - export PYTHONUNBUFFERED=true

script:
    # testing is done by running run_test.sh automatically during build
  - echo travis_fold:start:conda.build.package
  - conda build devtools/conda-recipe
  - echo travis_fold:end:conda.build.package

  # Upload new docs
  - bash -x devtools/ci/after_sucess.sh

env:
  - CONDA_PY=2.7 CONDA_NPY=1.7
  - CONDA_PY=2.7 CONDA_NPY=1.11
  - CONDA_PY=3.4 CONDA_NPY=1.10
  - CONDA_PY=3.5 CONDA_NPY=1.11
