package:
  name: ipynbtest
  version: !!str 0.1.0

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - docopt
    - jinja2

  run:
    - python
    - docopt
    - pyyaml
    - jinja2

about:
  home: https://github.com/jhprinz/ipynb-test
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
