package:
  name: ipynbtest
  version: "0.2.1"

build:
  preserve_egg_dir: True
  number: 0

source:
  path: ../../
#  git_url: ../../.git

requirements:
  build:
    - python
    - setuptools
    - docopt
    - jinja2

  run:
    - python
    - jupyter
    - jupyter_client
    - nbformat

test:
  requires:
    - matplotlib
  source_files:
    - ipynbtest/examples/ipynbtest_tutorial.ipynb

about:
  home: https://github.com/jhprinz/ipynb-test
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
