package:
  name: ipynbtest
  version: "0.1.1"

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - docopt
    - jinja2

  run:
    - python
    - jupyter_client
    - nbformat

test:
  files:
    - examples/ipynbtest_tutorial.py

about:
  home: https://github.com/jhprinz/ipynb-test
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
